steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/corretor-backend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/corretor-backend:latest',
      './backend'
    ]
    id: 'build-backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/corretor-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/corretor-frontend:latest',
      '--build-arg', 'REACT_APP_API_URL=https://corretor-backend-$PROJECT_ID.run.app',
      './frontend'
    ]
    id: 'build-frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/corretor-backend:$COMMIT_SHA']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/corretor-frontend:$COMMIT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'corretor-backend',
      '--image', 'gcr.io/$PROJECT_ID/corretor-backend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '4Gi',
      '--cpu', '2',
      '--timeout', '900',
      '--concurrency', '10',
      '--max-instances', '10',
      '--set-env-vars', 'PYTHONPATH=/app,PYTHONUNBUFFERED=1'
    ]
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'corretor-frontend',
      '--image', 'gcr.io/$PROJECT_ID/corretor-frontend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--timeout', '300',
      '--concurrency', '80',
      '--max-instances', '5'
    ]
    id: 'deploy-frontend'
    waitFor: ['push-frontend', 'deploy-backend']

# Configurações globais
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: '1200s'

# Imagens que serão armazenadas no Container Registry
images:
  - 'gcr.io/$PROJECT_ID/corretor-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/corretor-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/corretor-backend:latest'
  - 'gcr.io/$PROJECT_ID/corretor-frontend:latest'
